=begin pod

=head1 NAME

Date::YearDay - Provides additional methods for contructing or manipulating a Raku B<Date> object

=head1 SYNOPSIS

=begin code :lang<raku>

use Date::YearDay;

=end code

=head1 DESCRIPTION

Date::YearDay is ...

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2021 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
